# Ansible server
# sudo yum -y install epel-release
# sudo yum -y install ansible
# sudo yum -y install openssh-clients
## cd /home/vagrant/vagrant_shared/ansible
## cp private_keys/private_key ../../
## sudo chmod 0600 ../../private_key
## ansible-playbook -i hosts/dev.txt main.yml -u vagrant --private-key="../../private_key"
# key: key=val key=valはAnsibleの独自拡張。複雑だとちゃんと動かない
---
- name: install middlewares
  hosts: dev
  tasks:
  
#Ubuntuは初期状態でSELinuxはinstallされていない
#- name: disable selinux
#    become: yes
#    shell: bash setenforce 0
#    ignore_errors: true
#  - name: set selinux/config
#    become: yes
#    template:
#      src: templates/selinux_config
#      dest: /etc/selinux/config
#      owner: root
#      group: root
#      mode: 644

  - name: update apt list
    become: yes
    apt:
      update_cache: yes

  - name: install apache2
    become: yes
    apt: name=apache2 state=latest
  - name: start apache2
    become: yes
    service: name=apache2 state=started enabled=yes
    ignore_errors: true
  
  - name: install mariadb
    become: yes
    apt: name=mariadb-server state=latest
  - name: start mariadb
    become: yes
    service: name=mariadb state=started enabled=yes
    ignore_errors: true
  - name: set my.cnf
    become: yes
    template:
      src: templates/my.cnf
      dest: /etc/my.cnf
      owner: root
      group: root
      mode: 644
  - name: touch log files (/var/log/mysql/)
    become: yes
    file: path=/var/log/mysql           state=directory owner=mysql group=mysql mode=0755
  - name: touch log files (/var/log/mysql/slow.log)
    become: yes
    file: path=/var/log/mysql/slow.log  state=touch     owner=mysql group=mysql mode=0755
  - name: touch log files (/var/log/mysql/error.log)
    become: yes
    file: path=/var/log/mysql/error.log state=touch     owner=mysql group=mysql mode=0755
  
  - name: setup mariadb grant(install python3-pymysql)
    become: yes
    apt: name=python3-pymysql state=latest
  - name: setup mariadb grant(root grant1 root@localhost)
    become: yes
    mysql_user:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: 'root'
      host: 'localhost'
      password: 'foo'
      priv: '*.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes
    ignore_errors: true
  - name: restart mariadb
    become: yes
    service: name=mariadb state=restarted
    ignore_errors: true
  
  - name: install software-properties-common
    become: yes
    apt:     name=software-properties-common  state=latest
  - name: apt_repository ondrej/php
    become: yes
    apt_repository:
      validate_certs: no
      repo: 'ppa:ondrej/php'
      state: present
#ondrej/phpのphpには、ctype, fileinfo, json, openssl, pdo, tokenizerが含まれている
#laravel8, cakephpに必要なもの + php-cli, php-dev, php-gd, php-opcache, php-sqlite3, php8.1-xdebug
  - name: install php8.1
    become: yes
    apt:     name=php8.1             state=latest
  - name: install php8.1-bcmath
    become: yes
    apt:     name=php8.1-bcmath      state=latest
  - name: install php8.1-cli
    become: yes
    apt:     name=php8.1-cli         state=latest
  - name: install php8.1-dev
    become: yes
    apt:     name=php8.1-dev         state=latest
  - name: install php8.1-gd
    become: yes
    apt:     name=php8.1-gd          state=latest
  - name: install php8.1-intl
    become: yes
    apt:     name=php8.1-intl        state=latest
  - name: install php8.1-mbstring
    become: yes
    apt:     name=php8.1-mbstring    state=latest
  - name: install php8.1-mysql
    become: yes
    apt:     name=php8.1-mysql       state=latest
  - name: install php8.1-opcache
    become: yes
    apt:     name=php8.1-opcache     state=latest
  - name: install php8.1-sqlite3
    become: yes
    apt:     name=php8.1-sqlite3     state=latest
  - name: install php8.1-xdebug
    become: yes
    apt:     name=php8.1-xdebug      state=latest
  - name: install php8.1-xml
    become: yes
    apt:     name=php8.1-xml         state=latest
  - name: restart apache2
    become: yes
    service: name=apache2 state=restarted enabled=yes
    ignore_errors: true
  
  - name: install unzip
    become: yes
    apt:     name=unzip state=latest
  - name: install git
    become: yes
    apt:     name=git   state=latest

  - name: create directory (/tmp/composer)
    become: yes
    file: path=/tmp/composer state=directory mode=0777  
  - name: get composer to /tmp/composer
    get_url: url=https://getcomposer.org/installer dest=/tmp/composer/installer
  - name: install composer
    become: yes
    shell: chdir=/tmp/composer php installer
  - name: move composer
    become: yes
    shell: mv /tmp/composer/composer.phar /usr/local/bin/composer